version: '3.8'

services:
  game-server:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MAX_PLAYERS=8
      - SERVER_NAME=Heaven Burns Red Server
      - ENABLE_SAVE_SYNC=true
    volumes:
      - game-saves:/app/saves
      - game-config:/app/config
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import socket; socket.create_connection(('localhost', 8080))"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  game-saves:
  game-config: